config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#welcome'
  get '/users', to: "users#index"
  get "/users/:id", to: "users#show"
  get "/banished/", to: "banish#banished_way"
  post "/banish/:id", to: "banish#banish", as: "banish"

  #Routes for notícias
  resources :articles
 # get 'articles/index'
  #get "articles/index/:id", to: "articles#show"
  #get "articles/new"
  #post "articles/new"
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  validates :title, presence: true, length: { minimum: 2, maximum: 40 }
  validates :content, presence: true, length: {minimum: 2, maximum: 2000 }

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :articles

  validates :name, presence: true, length: { minimum: 2, maximum: 15 }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :user_banished?, if: :devise_controller?

    protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def user_banished?
    if user_signed_in?
      if current_user.banished?
        redirect_to banished_path
        sign_out current_user
      end
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = current_user.articles
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.create(articles_params)

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  private

  def articles_params
    params.require(:article).permit(:title, :sub_title, :content)
  end

end

app/controllers/banish_controller.rb
class BanishController < ApplicationController
  
  def banished_way
  end  

  def banish
        @user = User.find(params[:id])
        @user.banished = !@user.banished?
       if current_user.admin? && @user.save
        puts "User banished"
        redirect_to users_path
       else
        puts "Unprocessed entity"
        redirect_to users_path
       end
    end


    private

  def user_params
    params.require(:user).permit(:banished)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :user_banished?
  def welcome
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    if current_user.admin?
      @users = User.where.not(id: current_user.id)
    else
      redirect_to root_path
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:banished)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def my_link_to(text, href)
        href.gsub!(".", "/") 
        "<a href='#{href}'>#{text}</a>".html_safe
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/index.html.haml
%h1 Articles
- @index = 0
%table.table.table-hover
    %thead
        %tr
            %th{scope: "col"} #
            %th{scope: "col"} title
            %th{scope: "col"} sub title
            %th{scope: "col"} content
    %tbody
    - @articles.each do | article |
    - @index += 1 
        %tr
            %th{scope: "row"}= @index
            %td= my_link_to article.title, articles_path(article)
            %td= article.sub_title
            %td= article.content

app/views/articles/new.html.haml
%section.container
    %main.container
        %h1 New Article
        = form_with model: @article, url: articles_path do |f|
            %div.form-group
                = f.label :title
                = f.text_field :title, class: "form-control"
            %div.form-group
                = f.label :sub_title, "Subtitle"
                = f.text_field :sub_title, class: "form-control"
            %div.form-group
                = f.text_area :content, class: "form-control"
            = f.submit

app/views/articles/show.html.haml
%h1= @article.title
%h2= @article.sub_title
%p= @article.content

app/views/banish/banished_way.html.haml
%h1 You wore Banished!

app/views/home/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  %a.navbar-brand{href: root_path } Diário Online
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", type: "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
    %ul.navbar-nav.ml-auto
      %li.nav-item.active
        %a.nav-link{href: articles_path}
          Notícias
          %span.sr-only (current)
      - unless current_user
        %li.nav-item
          %a.nav-link{href: user_session_path } Login
      - else
        %li.nav-item
          %a.nav-link{href: destroy_user_session_path } Logout
      - if current_user
        - unless current_user.admin?
          %li.nav-item
            %a.nav-link{href: "#"} Amigos
        - else
          %li.nav-item
            %a.nav-link{href: "#"} Redação
          %li.nav-item
            %a.nav-link{href: users_path } Users
    %form.form-inline.my-2.my-lg-0
      %input.form-control.mr-sm-2{"aria-label" => "Search", placeholder: "Search", type: "search"}/
      %button.btn.btn-outline-success.my-2.my-sm-0{type: "submit"} Search

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Dol
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    
  %body
    /%p.notice= notice
    /%p.alert= alert
    = render 'home/navbar'
    = yield

app/views/users/index.html.haml
%h1 All Users
- @index = 0
%table.table.table-hover
    %thead
        %tr
            %th{scope: "col"} #
            %th{scope: "col"} name
            %th{scope: "col"} e-mail
            %th{scope: "col"} Admin?
            %th{scope: "col"} Banished?
    %tbody
    - @users.each do | user |
    - @index += 1 
        %tr
            %th{scope: "row"}= @index
            %td= my_link_to user.name, users_path(user)
            %td= user.email
            %td= user.admin?
            %td= user.banished?

app/views/users/show.html.haml
%h1 
    = @user.name
%section.card
    %table.table.table-hover
        %thead
            %tr
                %th{scope: "col"} e-mail
                %th{scope: "col"} Admin?
                %th{scope: "col"} Banished?
                %th{scope: "col"} Banish user 
        %tbody
        - [@user].each do | user |
            %tr
                %td= user.email
                %td= user.admin?
                %td= user.banished?
                %td
                    = form_with(url: banish_path, method: "post") do |f|
                        = f.hidden_field :user => {:user => {:id => user.id, :banished => true}}
                        - if !user.banished?
                            = f.submit "Banish"
                        - else
                            = f.submit "Reborn"
            
%td= my_link_to "All users", users_path
            